server:
  port: 8770
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/afashi/spring-cloud-config-demo
          searchPaths: respo
          username:
          password:
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/